language: cpp
compiler: gcc
script: make && make test

notifications:
  email:
    recipients:
      - benno.green@gmail.com
    on_success: never #default: change
    on_failure: always #default: always